name: Staging environment test
on:
  workflow_run:
    workflows: ["Staging environment deploy"]
    types:
      - completed
jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Set the correct Node version using nvm
        shell: bash -l {0}
        run: nvm install 16
      - name: Install AWS CDK
        run: npm install -g aws-cdk
